server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebanking
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Passeword1
  application:
    name: user-service
