def jarName     = "userService-0.0.1-SNAPSHOT.jar"
def jarPath     = "/home/aafif/upload/tools/repo/ma/tna/ebanking/userService/0.0.1-SNAPSHOT/${jarName}"
def deployPath  = "/home/aafif/upload/microService/ebanking/userService/"

pipeline { 
    agent any  
    stages { 
        stage('Build') { 
            steps {
                sh "${mavenPath} -Precette clean install -DJAVA_HOME=${javaHome}"
                }
        } 
        stage('SonarQube analysis') {
            steps {
                withSonarQubeEnv('My SonarQube Server') {
                    sh "${mavenPath} -Psonar sonar:sonar"
                }
            }
        }
        stage('kill jar') { 
            steps {
                    catchError {
                              sh "jps -l | grep ${jarName} || exit 0"
                              sh "sh ${killerSh} ${jarName} || exit 0"
                              sh "jps -l | grep ${jarName} || exit 0"
                        }
                } 
            } 
        stage("Deploy & Start") {
            steps {
                sh " cp ${jarPath} ${deployPath}"
                dir("${deployPath}") {
                      sh "pwd"
                      sh "JENKINS_NODE_COOKIE=dontKillMe nohup ${javaHome}/jre/bin/java -jar -Xms128m -Xmx512m ${jarName} & "
                      sh "sleep 10"
                      sh "tail -50 logs/application-logger.log"
                      sh "tail -100 logs/application-logger.log | grep 'Started ' | tail -1"
                }
            } 
        }   
    }
}